### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by acclaw297** [GovanifY/KH2FM_Toolkit#2] opened 2021-07-28 20:36 UTC
I been honestly strugglimg with this access denied problem.

**Comment by GovanifY** [comment] 2021-07-28 20:42
uhhh I'm going to need more details than this to be able to help

**Comment by acclaw297** [comment] 2021-07-31 00:07
It would show this after i press enter
An error has occured when trying to open your iso:
System.UnauthorizedAccessException: Access to the path 'C:\Users\adria\OneDrive\Desktop\New folder\KH2FM.ISO' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at KH2FM_Toolkit.Program.Main(String[] args)
I'm trying to get the Vanties mod but that's the blockage.
Aand also to the point where the file can't be found either.

**Comment by GovanifY** [comment] 2021-07-31 04:14
It seems like you don't have the permissions to read/rebuild the iso. Maybe try in a path that's not inside OneDrive?

**Comment by acclaw297** [comment] 2021-07-31 11:36
alright
But how exactly can I change the path?
Now I change it but still say the file can't be found
Failed to open file: Could not find file 'C:\Users\adria\PATCHER-LAPTOP-6I3NV81F\KH2FM.ISO'.

**Comment by GovanifY** [comment] 2021-08-01 15:20
you have to move the iso from another folder than onedrive on your computer

**Comment by acclaw297** [comment] 2021-08-01 19:58
Not gonna lie I don't what you meant there

**Comment by GovanifY** [comment] 2021-08-02 11:22
KH2FM.ISO > right-click > copy file > move in another folder using windows explorer > right-click > paste file

**Comment by acclaw297** [comment] 2021-08-02 22:32
Yes I did it all I had to do was name it KH2FM

**Comment by GovanifY** [comment] 2021-08-02 23:42
Well if you did it all I believe everything is good then.
I'm going to go ahead and close this issue as this is a place to report software bugs, not to act as a user support, and that this is indeed intended behaviour: I cannot read files which your OS won't let me read

**Closed as completed by GovanifY** 2021-08-02 23:42 UTC

**Comment by acclaw297** [comment] 2021-08-03 00:02
Thanks
